set nocompatible
filetype plugin on

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

"-------------------------------------------------------------------------------
"  Vundle manage Vundle, required
"-------------------------------------------------------------------------------
Plugin 'gmarik/Vundle.vim'

"-------------------------------------------------------------------------------
"  Auto Complete features
"-------------------------------------------------------------------------------
Plugin 'AutoComplPop'

"-------------------------------------------------------------------------------
"  Colors and themes
"-------------------------------------------------------------------------------
Plugin 'tomasr/molokai'
Plugin 'bling/vim-airline'

"-------------------------------------------------------------------------------
"  Git
"-------------------------------------------------------------------------------
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'

"-------------------------------------------------------------------------------
"  Go
"-------------------------------------------------------------------------------
Plugin 'fatih/vim-go'
Plugin 'garyburd/go-explorer'

"-------------------------------------------------------------------------------
"  Html
"-------------------------------------------------------------------------------
Plugin 'othree/html5.vim'
Plugin 'mattn/emmet-vim'

"-------------------------------------------------------------------------------
"  Javascript
"-------------------------------------------------------------------------------
Plugin 'burnettk/vim-angular'
Plugin 'pangloss/vim-javascript'
Plugin 'othree/javascript-libraries-syntax.vim'
"Plugin 'kchmck/vim-coffee-script'"

"-------------------------------------------------------------------------------
"  Search & Navigation
"-------------------------------------------------------------------------------
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'kien/ctrlp.vim'

"-------------------------------------------------------------------------------
"  Text & Utilities
"-------------------------------------------------------------------------------
Plugin 'majutsushi/tagbar'

"-------------------------------------------------------------------------------
"  Tmux integration
"-------------------------------------------------------------------------------
Plugin 'benmills/vimux'
Plugin 'christoomey/vim-tmux-navigator'

call vundle#end()
filetype plugin indent on

" override default configurations
source $HOME/.vim/colors.vim
source $HOME/.vim/config.vim
source $HOME/.vim/shortcuts.vim
source $HOME/.vim/autocommands.vim
source $HOME/.vim/functions.vim
source $HOME/.vim/plugins.vim
