set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

"-------------------------------------------------------------------------------
"  Vundle manage Vundle, required
"-------------------------------------------------------------------------------
Plugin 'gmarik/Vundle.vim'

"-------------------------------------------------------------------------------
"  Colors and themes
"-------------------------------------------------------------------------------
Plugin 'tomasr/molokai'
Plugin 'bling/vim-airline'

"-------------------------------------------------------------------------------
"  Git
"-------------------------------------------------------------------------------
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'

"-------------------------------------------------------------------------------
"  Go
"-------------------------------------------------------------------------------
Plugin 'fatih/vim-go'
Plugin 'garyburd/go-explorer'

"-------------------------------------------------------------------------------
"  Search & Navigation
"-------------------------------------------------------------------------------
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'Valloric/YouCompleteMe'

"-------------------------------------------------------------------------------
"  Text & Utilities
"-------------------------------------------------------------------------------
Plugin 'majutsushi/tagbar'

call vundle#end()
filetype plugin indent on

" override default configurations
source $HOME/.vim/colors.vim
source $HOME/.vim/config.vim
source $HOME/.vim/shortcuts.vim
source $HOME/.vim/autocommands.vim
source $HOME/.vim/functions.vim
source $HOME/.vim/plugins.vim
