# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# For Solarized
export TERM="xterm-256color"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Comment this out to disable bi-weekly auto-update checks
#DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(aws bgnotify boot2docker bower brew bundler cp colorize dirhistory docker docker-compose gem git git-extras git-remote-branch gnu-utils go grunt history history-substring-search man mvn nmap node npm nvm oc postgres rake rvm sudo ssh-agent tmux tmuxinator vagrant web-search)

#Configure oh-my-zsh
source $ZSH/oh-my-zsh.sh

#Configure Prefered keybindings
bindkey '^R' history-incremental-search-backward
bindkey "^A" beginning-of-line
bindkey "^D" delete-char
bindkey "^E"  end-of-line
bindkey ' ' magic-space
bindkey '^[[1;5C' forward-word                        # [Ctrl-RightArrow] - move forward one word
bindkey '^[[1;5D' backward-word                       # [Ctrl-LeftArrow] - move backward one word

export DEFAULT_USER=rafaelbenevides

export GOPATH=$HOME/go
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/
export FORGE_HOME=~/java/forge/

#Export PATH variable
export PATH=$HOME/.rvm/bin:$JAVA_HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$GOPATH/bin:$FORGE_HOME/bin
