---
  #Link dot files
  - name: Symlink my dotfiles
    file: src={{ dotfilespath }}/dotfiles/{{ item }}
          dest=~/.{{ item }}
          state=link
          force=yes
    with_items:
        - zshrc
        - gitconfig
        - gitignore
        - vimrc
        - tmux.conf