  - name: Linux dnf - Get sure WGET is available
    dnf: name=wget state=present

  - name: Linux dnf - Make suere GIT is available
    dnf: name=git state=present

  - name: Linux dnf - Make sure CURL is available
    dnf: name=curl state=present

  - name: Linux dnf - Make sure ZSH is available
    dnf: name=zsh state=present

  - name: Linux dnf - Make sure Docker ZSH completions is available
    dnf: name=docker-zsh-completion state=present

  - name: Linux dnf - Make sure CTAGS  is available
    dnf: name=ctags state=present

  - name: Linux dnf - Make sure CMAKE  is available
    dnf: name=cmake state=present

  - name: Linux dnf - Make sure TMUX  is available
    dnf: name=tmux state=present

  - name: Linux shell - Retrieve the current shell
    command: echo $SHELL
    register: shell

  - name: Linux shell - Set the Default shell to ZSH
    command: usermod -s /bin/zsh {{ lookup('env','USER') }}
    when: shell.stdout != "/bin/zsh"
    become: yes
    become_method: sudo

