---
- hosts: localhost

  pre_tasks:
    - include: tasks/mac/brewdependencies.yaml
      when: ansible_distribution == "MacOSX"
    - include: tasks/linux/dnfdependencies.yaml
      when: ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 22

  roles:
    #- { role: common }

  tasks:
    - include: tasks/linkdotfiles.yaml
    - include: tasks/vim.yaml
    - include: tasks/ohmyzsh.yaml
    - include: tasks/tmux.yaml
