---
- hosts: localhost
  
  pre_tasks:
    - include: tasks/brewdependencies.yaml
      when: ansible_distribution == "MacOSX"

  roles:
    #- { role: common }

  tasks:
    - include: tasks/pip.yaml
    - include: tasks/linkdotfiles.yaml
    - include: tasks/vim.yaml
    - include: tasks/ohmyzsh.yaml
    - include: tasks/tmux.yaml
    - include: tasks/pip.yaml
    - include: tasks/did.yaml
